using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Da침o : MonoBehaviour
{
    public GameObject explosionPrefab;

    public LifePlayer player;

    private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.CompareTag("Obstaculo"))
        {
            // Instanciar el prefab de la animaci칩n del power-up
            Instantiate(explosionPrefab, transform.position, Quaternion.identity);

            Debug.Log("da침o");
            Destroy(explosionPrefab, 1f);

            player.TakeDamage(1);

            // Eliminar el objeto que colision칩 
            Destroy(other.gameObject);

        }
    }
}
